packages:
  - "apps/*"
  - "packages/*"
overrides:
  test-exclude>glob: '^10.0.0'

allowBuilds:
  "@parcel/watcher": false
  '@scarf/scarf': false
  bcrypt: true
  esbuild: set this to true or false
  sharp: false
  unrs-resolver: false
