import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Footer from 'components/common/footer/Footer';
import { DesktopNavbar } from 'components/common/navbar/DesktopNavbar';
import { MobileNavbar } from 'components/common/navbar/MobileNavbar';
import SiteLoaderGate from 'components/layout/SiteLoaderGate';
import './index.css';

const geistSans = localFont({
  src: './fonts/Gabarito-VariableFont_wght.ttf',
  variable: '--font-gabarito-sans'
});
const geistMono = localFont({
  src: './fonts/GeistMono-VariableFont_wght.ttf',
  variable: '--font-geist-mono'
});
const orbitron = localFont({
  src: './fonts/Orbitron-VariableFont_wght.ttf',
  variable: '--font-orbitron'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable}`}
      >
        <SiteLoaderGate>
          <DesktopNavbar />
          <MobileNavbar />
          {children}
          <Footer />
        </SiteLoaderGate>
      </body>
    </html>
  );
}
